title: Vincent
brief-intro: Android and Python Coder
description: 
google_analytics: 
show_downloads: false
#theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions


description_footer: 来自徐代龙的个人专栏！

paginate: 6